---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  requirements_path: requirements.yml
  require_chef_for_busser: false
  require_ansible_omnibus: false
  ansible_version: 2.7.16-1ppa~trusty
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ignore_paths_from_root:
    - .kitchen
  ssh_known_hosts:
    - github.com

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: ubuntu:14.04
      platform: ubuntu
      privileged: true
      provision_command:
        - apt-get update
        - apt-get install -y software-properties-common apt-transport-https
        - add-apt-repository ppa:ansible/ansible-2.7
        - apt-get update
        - apt-get install -y python-pip python-openssl python-pyasn1
        - pip install ndg-httpsclient passlib docker
        - curl -s -L https://www.chef.io/chef/install.sh | ${sudo} bash -s -- -v 12.2.1

  - name: centos-7.2
    driver_config:
      image: centos/systemd
      platform: centos
      privileged: true
      run_command: /sbin/init
      provision_command:
        - yum install -y iproute tuned epel-release ansible git cronie initscripts libselinux-python policycoreutils-python
        # https://github.com/CentOS/CentOS-Dockerfiles/issues/173
        - systemctl enable systemd-user-sessions.service && ln -s /usr/lib/systemd/system/systemd-user-sessions.service /etc/systemd/system/default.target.wants/systemd-user-sessions.service

suites:
  - name: default
    driver:
      network:
        - ["private_network", { ip: "172.29.129.172" }]

transport:
  forward_agent: true
