- src: git@github.com:o2-priority/ansible-java.git
  version: master
  scm: git
  name: o2-priority.java

- src: git@github.com:o2-priority/ansible-jenkins.git
  version: jenkins-upgrade
  scm: git
  name: o2-priority.jenkins
